all: flash

# MCUMODE: MCU_MAIN, MCU_BRAKES, MCU_ENCODERS, MCU_MAIN
MCUMODE=MCU_MAIN

# TODO fpack struct
test: main_avr.c core.c encoders.c comm_avr.c msgs.c comm.c ringbuf.c motors.c motors_avr.c pwm_avr.c uartbuf.c uart_avr.c analog.c adc.c
	avr-gcc -mmcu=atmega2560 -D$(MCUMODE) -Wall -Wextra -Os -DF_CPU=16000000 $^ -o $@
	avr-size -d $@
	avr-objcopy -j .text -j .data -O ihex $@ $@.hex

flash: test
	avrdude -p m2560 -c stk500v2 -P /dev/ttyACM0 -b 115200 -U test.hex
